# Generated by Django 5.2.15 on 2026-06-11 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Buxoro shahri', max_length=100)),
                ('geometry', models.JSONField(help_text='GeoJSON Polygon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shahar chegarasi',
                'verbose_name_plural': 'Shahar chegaralari',
            },
        ),
        migrations.CreateModel(
            name='LandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)')),
                ('geometry_type', models.CharField(choices=[('Point', 'Nuqta'), ('LineString', 'Chiziq'), ('Polygon', 'Poligon')], default='Polygon', max_length=20)),
                ('color', models.CharField(default='#3388ff', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Yer kategoriyasi',
                'verbose_name_plural': 'Yer kategoriyalari',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='PublicLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('cadastral_number', models.CharField(blank=True, max_length=100, verbose_name='Kadastr raqami')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Manzil')),
                ('description', models.TextField(blank=True)),
                ('geometry', models.JSONField(help_text='GeoJSON geometriya')),
                ('area_sqm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maydon (m²)')),
                ('length_m', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Uzunlik (m)')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('construction', 'Qurilish jarayonida'), ('damaged', 'Zararlangan'), ('closed', 'Yopiq'), ('planned', 'Rejalashtirilgan')], default='active', max_length=20)),
                ('responsible_org', models.CharField(blank=True, max_length=255, verbose_name="Mas'ul tashkilot")),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lands', to='lands.landcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lands', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Umumfoydalanishdagi yer',
                'verbose_name_plural': 'Umumfoydalanishdagi yerlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LandAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='land_attachments/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Rasm'), ('document', 'Hujjat'), ('other', 'Boshqa')], default='image', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lands.publicland')),
            ],
            options={
                'verbose_name': 'Biriktirma',
                'verbose_name_plural': 'Biriktirmalar',
            },
        ),
        migrations.AddIndex(
            model_name='publicland',
            index=models.Index(fields=['status'], name='lands_publi_status_ecd531_idx'),
        ),
        migrations.AddIndex(
            model_name='publicland',
            index=models.Index(fields=['category'], name='lands_publi_categor_4d0b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='publicland',
            index=models.Index(fields=['created_at'], name='lands_publi_created_4c5a57_idx'),
        ),
    ]
