# Generated by Django 5.2.15 on 2026-07-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityboundary',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Administrativ chegara', 'verbose_name_plural': 'Administrativ chegaralar'},
        ),
        migrations.AddField(
            model_name='cityboundary',
            name='boundary_type',
            field=models.CharField(choices=[('city', 'Shahar'), ('region', 'Viloyat')], default='city', max_length=20),
        ),
        migrations.AddField(
            model_name='cityboundary',
            name='code',
            field=models.SlugField(default='bukhara_city', unique=True),
        ),
        migrations.AddField(
            model_name='cityboundary',
            name='color',
            field=models.CharField(default='#ff6b00', max_length=7),
        ),
        migrations.AddField(
            model_name='cityboundary',
            name='dash_array',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cityboundary',
            name='fill_opacity',
            field=models.FloatField(default=0.04),
        ),
        migrations.AddField(
            model_name='cityboundary',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cityboundary',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityboundary',
            name='weight',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
