# Generated by Django 5.2.15 on 2026-07-27 04:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_alter_cityboundary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityboundary',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Административная граница', 'verbose_name_plural': 'Административные границы'},
        ),
        migrations.AlterModelOptions(
            name='landattachment',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterModelOptions(
            name='landcategory',
            options={'ordering': ['order', 'name_uz'], 'verbose_name': 'Категория земель', 'verbose_name_plural': 'Категории земель'},
        ),
        migrations.AlterModelOptions(
            name='publicland',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Земля общего пользования', 'verbose_name_plural': 'Земли общего пользования'},
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='boundary_type',
            field=models.CharField(choices=[('city', 'Город'), ('region', 'Область')], default='city', max_length=20, verbose_name='Тип границы'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='code',
            field=models.SlugField(default='bukhara_city', unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='color',
            field=models.CharField(default='#ff6b00', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='dash_array',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Пунктир (dash)'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='fill_opacity',
            field=models.FloatField(default=0.04, verbose_name='Прозрачность заливки'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='geometry',
            field=models.JSONField(help_text='GeoJSON Polygon', verbose_name='Геометрия'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видима'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='name',
            field=models.CharField(default='Город Бухара', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='cityboundary',
            name='weight',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Толщина линии'),
        ),
        migrations.AlterField(
            model_name='landattachment',
            name='file',
            field=models.FileField(upload_to='land_attachments/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='landattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ'), ('other', 'Другое')], default='image', max_length=20, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='landattachment',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lands.publicland', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='landattachment',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='landattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='landattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='color',
            field=models.CharField(default='#3388ff', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='geometry_type',
            field=models.CharField(choices=[('Point', 'Точка'), ('LineString', 'Линия'), ('Polygon', 'Полигон')], default='Polygon', max_length=20, verbose_name='Тип геометрии'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постановки на учёт'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='area_sqm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='cadastral_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lands', to='lands.landcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lands', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='geometry',
            field=models.JSONField(help_text='Геометрия GeoJSON', verbose_name='Геометрия'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='length_m',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина (м)'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='responsible_org',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответственная организация'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('construction', 'Строительство'), ('damaged', 'Повреждён'), ('closed', 'Закрыт'), ('planned', 'Запланирован')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lands', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
    ]
