# Generated by Django 5.2.15 on 2026-07-28 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_alter_cityboundary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('geometry', models.JSONField(blank=True, null=True, verbose_name='Геометрия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Махалля',
                'verbose_name_plural': 'Махалли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('description', models.TextField(verbose_name='Описание изменения')),
                ('delta_area_ha', models.FloatField(default=0, verbose_name='Δ площадь (га)')),
                ('delta_length_km', models.FloatField(default=0, verbose_name='Δ длина (км)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='approved', max_length=20, verbose_name='Статус')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Запись мониторинга',
                'verbose_name_plural': 'Записи мониторинга',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('year_type', models.CharField(choices=[('monitoring', 'Мониторинг земель'), ('urbanization', 'Урбанизация')], default='monitoring', max_length=20, verbose_name='Тип')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Год мониторинга',
                'verbose_name_plural': 'Годы мониторинга',
                'ordering': ['year_type', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ObjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('geometry', models.JSONField(blank=True, null=True, verbose_name='Геометрия')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='Площадь (м²)')),
                ('length_m', models.FloatField(blank=True, null=True, verbose_name='Длина (м)')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Статус')),
                ('condition', models.CharField(blank=True, max_length=20, verbose_name='Состояние')),
                ('change_note', models.CharField(blank=True, max_length=500, verbose_name='Примечание об изменении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Версия объекта',
                'verbose_name_plural': 'Версии объектов',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сообщение администратора',
                'verbose_name_plural': 'Сообщения администратора',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UrbanizationLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('layer_kind', models.CharField(choices=[('urban', 'Городская территория'), ('agriculture', 'Сельхозугодья'), ('other', 'Прочее')], default='urban', max_length=20, verbose_name='Тип слоя')),
                ('geometry', models.JSONField(blank=True, null=True, verbose_name='Геометрия')),
                ('area_ha', models.FloatField(default=0, verbose_name='Площадь (га)')),
                ('growth_pct', models.FloatField(default=0, verbose_name='Прирост (%)')),
                ('color', models.CharField(default='#e74c3c', max_length=7, verbose_name='Цвет')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видим')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Слой урбанизации',
                'verbose_name_plural': 'Слои урбанизации',
                'ordering': ['year', 'layer_kind'],
            },
        ),
        migrations.AlterModelOptions(
            name='publicland',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Объект реестра (земля общего пользования)', 'verbose_name_plural': 'Объекты реестра'},
        ),
        migrations.AddField(
            model_name='publicland',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', 'Хорошее'), ('normal', 'Удовлетворительное'), ('bad', 'Плохое')], default='good', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='publicland',
            name='data_source',
            field=models.CharField(blank=True, default='GIS / OSM', max_length=200, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='publicland',
            name='mahalla',
            field=models.CharField(blank=True, max_length=200, verbose_name='Махалля'),
        ),
        migrations.AddField(
            model_name='publicland',
            name='monitoring_year',
            field=models.PositiveIntegerField(default=2026, help_text='Актуальный год версии объекта', verbose_name='Год мониторинга'),
        ),
        migrations.AddField(
            model_name='publicland',
            name='public_id',
            field=models.CharField(blank=True, help_text='Например PARK-001, ROAD-I-001', max_length=40, null=True, unique=True, verbose_name='Публичный ID'),
        ),
        migrations.AddField(
            model_name='publicland',
            name='road_class',
            field=models.CharField(blank=True, choices=[('magistral', 'Магистральные'), ('shahar', 'Городские / районные'), ('mahalliy', 'Местные'), ('piyoda', 'Пешеходные')], default='', max_length=20, verbose_name='Класс дороги'),
        ),
        migrations.AlterField(
            model_name='publicland',
            name='status',
            field=models.CharField(choices=[('active', 'Хорошее / Активен'), ('construction', 'Строительство'), ('damaged', 'Повреждён'), ('closed', 'Закрыт'), ('planned', 'Запланирован')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='publicland',
            index=models.Index(fields=['public_id'], name='lands_publi_public__8e1a58_idx'),
        ),
        migrations.AddIndex(
            model_name='publicland',
            index=models.Index(fields=['monitoring_year'], name='lands_publi_monitor_a93149_idx'),
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='lands.publicland', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Записал'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringyear',
            unique_together={('year', 'year_type')},
        ),
        migrations.AddField(
            model_name='objectversion',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lands.publicland', verbose_name='Объект'),
        ),
        migrations.AlterUniqueTogether(
            name='objectversion',
            unique_together={('land', 'year')},
        ),
    ]
