# Generated by Django 5.2.15 on 2026-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Главный администратор'), ('specialist', 'Специалист'), ('monitor', 'Сотрудник мониторинга'), ('observer', 'Публичный пользователь')], default='observer', max_length=20, verbose_name='Роль'),
        ),
    ]
