# Generated by Django 5.2.15 on 2026-07-27 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_alter_cityboundary_options_and_more'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Запись об изменении', 'verbose_name_plural': 'История изменений'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемные участки'},
        ),
        migrations.AlterField(
            model_name='changelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Создано'), ('updated', 'Обновлено'), ('status_changed', 'Статус изменён'), ('geometry_changed', 'Геометрия изменена'), ('deleted', 'Удалено')], max_length=20, verbose_name='Тип изменения'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='lands.publicland', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Старое значение'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='Назначен'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='lands.publicland', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='Сообщил'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Решено'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=20, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('closed', 'Закрыта')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
