# Generated by Django 5.2.15 on 2026-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_changelog_options_alter_issue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проблемный участок', 'verbose_name_plural': 'Проблемные участки'},
        ),
        migrations.AddField(
            model_name='issue',
            name='geometry',
            field=models.JSONField(blank=True, null=True, verbose_name='Геометрия (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='geometry_kind',
            field=models.CharField(choices=[('Point', 'Точка'), ('LineString', 'Линия'), ('Polygon', 'Полигон')], default='Point', max_length=20, verbose_name='Тип геометрии'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Устранено'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Устранена'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
