# Generated by Django 5.0.7 on 2026-09-01 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_issue_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationOnSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=500, verbose_name='Sayt URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Murojaat sayti',
                'verbose_name_plural': 'Murojaat saytlari',
                'ordering': ['application_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Murojaat turi',
                'verbose_name_plural': 'Murojaat turlari',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(verbose_name='Описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок (UZ)'),
        ),
        migrations.CreateModel(
            name='ApplicationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField(blank=True, verbose_name='Tahlil matni')),
                ('match_score', models.FloatField(default=0, verbose_name='Moslik %')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Yuborilgan')], default='draft', max_length=20, verbose_name='Holat')),
                ('external_payload', models.JSONField(blank=True, default=dict, verbose_name="Tashqi sayt ma'lumoti")),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_submissions', to='monitoring.issue', verbose_name='Muammo')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='monitoring.applicationonsite', verbose_name='Sayt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='monitoring.applicationtype', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Murojaat yozuvi',
                'verbose_name_plural': 'Murojaat yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='applicationonsite',
            name='application_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='monitoring.applicationtype', verbose_name='Turi'),
        ),
    ]
