# Generated by Django 5.0.7 on 2026-09-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_applicationonsite_applicationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Tahlil uchun: qanday muammolar shu tashkilotga tegishli', verbose_name='Tavsif'),
        ),
    ]
